name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint || true

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3' # Replace with your required version

      - name: Build only
        run: |
            xcodebuild clean build \
            -project CoreDataExercise.xcodeproj \
            -scheme CoreDataExercise \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
